export interface Product {
  name: string;
  nombre: string;
  precio: number;
  standard_rate?: number;
  rate?: number;
  categoria: string;
  category?: string;
  codigo: string;
  item_code?: string;
  item_name?: string;
  tipo?: string;
  unidad?: string;
  descripcion: string;
  imagen?: string;
  tax?: string;
  isactive: number | boolean;
  is_out_of_stock: number | boolean;
  company_id: string;
  tax_id?: string;
  tax_value?: number;
  iva?: number;
  tax_rate?: number;
  controlar_inventario?: number | boolean;
  maneja_stock?: number | boolean;
  manage_stock?: number | boolean;
  manages_stock?: number | boolean;
  unidad_inventario?: string;
  stock_actual?: number;
  current_stock?: number;
  track_stock?: boolean | number;
  minimum_stock?: number;
  is_low_stock?: boolean | number;
  stock?: number;
  stock_minimo?: number;
  permitir_stock_negativo?: number | boolean;
  ultima_actualizacion_stock?: string;
  stock_inicial?: number;
  stock_ajuste?: number;
}
