name: Build & Deploy to Contabo (/pos)
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build (production with /pos)
        run: npx ng build

      # Empaqueta exactamente dist/angular/browser
      - name: Package artifact
        run: tar -czf dist.tgz -C dist/angular/browser .

      - name: Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}     # normalmente 'frappe'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist.tgz"
          target: "/home/frappe/frappe-bench/pos/"

      - name: Activate release (atomic swap)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            BASE=/home/frappe/frappe-bench/pos
            TS=$(date +%Y%m%d%H%M%S)
            REL=$BASE/releases/$TS
            mkdir -p "$REL"
            tar -xzf $BASE/dist.tgz -C "$REL"
            rm -f $BASE/dist.tgz
            ln -sfn "$REL" $BASE/current
            # Mantener solo 5 releases
            ls -1dt $BASE/releases/* | tail -n +6 | xargs -r rm -rf
            echo "Deployed $REL"
            if command -v nginx >/dev/null 2>&1; then
              sudo nginx -t && sudo systemctl reload nginx || true
            fi
